// ./RootLayout.tsx
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.scss';
import { AuthProvider } from '@/context/AuthContext';
import Header from '@/components/Header';
import { Container, Box } from '@mui/material';
import Footer from '@/components/Footer';
import Providers from './Providers';

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import { CONTENT_WIDTH } from '@/config/config';

import Script from 'next/script'; // 스크립트 가져오기

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'StudyOLA Store',
  description: 'Generated by collegenie.AI Company',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* Google Tag Manager 스크립트 */}
        <Script id="gtm-script" strategy="afterInteractive">
          {`
            (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-5G29CQ49');
          `}
        </Script>

        {/* 기존 Google Analytics 및 Google Ads 스크립트 */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-3LRTM2ZHNW"
          strategy="afterInteractive"
        />
        <script 
          src="https://developers.kakao.com/sdk/js/kakao.js" 
          async 
          defer
        ></script>

        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            // Google Analytics 초기화
            gtag('config', 'G-3LRTM2ZHNW');
            gtag('config', 'G-J8WTC42L9Q');            

            // Google Ads 초기화
            gtag('config', 'AW-16734880235');
          `}
        </Script>
      </head>
      <body
        className={inter.className}
        style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}
      >
        {/* Google Tag Manager noscript 태그 */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-5G29CQ49"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          ></iframe>
        </noscript>

        <Providers>
          {/* ThemeProvider가 적용된 Providers */}
          <AuthProvider>
            <Header />
            <Box sx={{ display: 'flex', flexDirection: 'column', flexGrow: 1 }}>
              <Container
                maxWidth="lg"
                sx={{
                  maxWidth: {
                    xl: `${CONTENT_WIDTH}px`,
                    lg: '100%', // lg 이하에서 최대 너비 100%
                    md: '100%', // md 이하에서 최대 너비 100%
                    sm: '100%', // sm 이하에서 최대 너비 100%
                    xs: '100%', // xs 이하에서 최대 너비 100%
                  },
                  mx: 'auto',
                  flexGrow: 1,
                }}
              >
                {children}
              </Container>
            </Box>
            <Footer />
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
