# Generated by Django 5.2 on 2025-04-03 12:22

import django.core.files.storage
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to=store.models.get_file_upload_path),
        ),
    ]
