// src/config/data.ts
export const accountData = {
  email: 'studyola@gmail.com',
  userName: 'oalist',
};

export const downloadsData = [
  {
    grade: 'USA grade 2',
    subject: 'Liberal Arts',
    questionInfo: 'Q1 Middle School Acids, Bases, and...',
    downloadDate: '2024-07-24',
    report: 'Write',
  },
  {
    grade: 'USA grade 3',
    subject: 'Mathematics',
    questionInfo: 'Q2 Middle School Algebra and Geometry',
    downloadDate: '2024-07-25',
    report: 'Write',
  },
  {
    grade: 'USA grade 4',
    subject: 'Science',
    questionInfo: 'Q3 Middle School Physics and Chemistry',
    downloadDate: '2024-07-26',
    report: 'Write',
  },
  {
    grade: 'USA grade 5',
    subject: 'History',
    questionInfo: 'Q4 Middle School World History',
    downloadDate: '2024-07-27',
    report: 'Write',
  },
  {
    grade: 'USA grade 6',
    subject: 'Geography',
    questionInfo: 'Q5 Middle School Geography',
    downloadDate: '2024-07-28',
    report: 'Write',
  },
  {
    grade: 'USA grade 7',
    subject: 'Biology',
    questionInfo: 'Q6 Middle School Biology',
    downloadDate: '2024-07-29',
    report: 'Write',
  },
  {
    grade: 'USA grade 8',
    subject: 'English',
    questionInfo: 'Q7 Middle School English Literature',
    downloadDate: '2024-07-30',
    report: 'Write',
  },
];

export const paymentsData = [
  {
    date: '2024-07-24',
    title: 'Q1 Middle School Acids, Bases, and...',
    totalAmount: 5.00,
    orderId: 'StudyOla-1234523',
    receipt: 'Receipt',
  },
  {
    date: '2024-07-25',
    title: 'Q2 Middle School Algebra and Geometry',
    totalAmount: 10.00,
    orderId: 'StudyOla-1234524',
    receipt: 'Receipt',
  },
  {
    date: '2024-07-26',
    title: 'Q3 Middle School Physics and Chemistry',
    totalAmount: 15.00,
    orderId: 'StudyOla-1234525',
    receipt: 'Receipt',
  },
  {
    date: '2024-07-27',
    title: 'Q4 Middle School World History',
    totalAmount: 20.00,
    orderId: 'StudyOla-1234526',
    receipt: 'Receipt',
  },
  {
    date: '2024-07-28',
    title: 'Q5 Middle School Geography',
    totalAmount: 25.00,
    orderId: 'StudyOla-1234527',
    receipt: 'Receipt',
  },
  {
    date: '2024-07-29',
    title: 'Q6 Middle School Biology',
    totalAmount: 30.00,
    orderId: 'StudyOla-1234528',
    receipt: 'Receipt',
  },
  {
    date: '2024-07-30',
    title: 'Q7 Middle School English Literature',
    totalAmount: 35.00,
    orderId: 'StudyOla-1234529',
    receipt: 'Receipt',
  },
];

export const reportDetailsData = [
  {
    grade: 'USA grade 2',
    subject: 'Liberal Arts',
    title: 'Q1 Middle School Acids, Bases, and...',
    registrationDate: '2024-07-24',
    questionType: 'Suggestions',
    processingResult: 'Progress',
    learnMore: 'Learn more',
  },
  {
    grade: 'USA grade 3',
    subject: 'Mathematics',
    title: 'Q2 Middle School Algebra and Geometry',
    registrationDate: '2024-07-25',
    questionType: 'Error',
    processingResult: 'Pending',
    learnMore: 'Learn more',
  },
  {
    grade: 'USA grade 4',
    subject: 'Science',
    title: 'Q3 Middle School Physics and Chemistry',
    registrationDate: '2024-07-26',
    questionType: 'Suggestions',
    processingResult: 'Completed',
    learnMore: 'Learn more',
  },
  {
    grade: 'USA grade 5',
    subject: 'History',
    title: 'Q4 Middle School World History',
    registrationDate: '2024-07-27',
    questionType: 'Error',
    processingResult: 'Progress',
    learnMore: 'Learn more',
  },
  {
    grade: 'USA grade 6',
    subject: 'Geography',
    title: 'Q5 Middle School Geography',
    registrationDate: '2024-07-28',
    questionType: 'Suggestions',
    processingResult: 'Pending',
    learnMore: 'Learn more',
  },
  {
    grade: 'USA grade 7',
    subject: 'Biology',
    title: 'Q6 Middle School Biology',
    registrationDate: '2024-07-29',
    questionType: 'Error',
    processingResult: 'Completed',
    learnMore: 'Learn more',
  },
  {
    grade: 'USA grade 8',
    subject: 'English',
    title: 'Q7 Middle School English Literature',
    registrationDate: '2024-07-30',
    questionType: 'Suggestions',
    processingResult: 'Progress',
    learnMore: 'Learn more',
  },
];
