export const items = [
  {
    id: 1,
    write_user_name: '김종필',
    subject: 'Math',
    type: 'Short Answer',
    grade: 'USA grade 1',
    unit: 'Addition and Subtraction',
    detailed_section: 'Numbers 0 to 100',
    difficulty: 1,
    title: 'Q1 Multivariable calculus Derivatives of multivariable functions',
    description: '- 30문제 PDF',
    price: '5.00',
    pages: 2,
    problems: 7,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 2,
    write_user_name: '김종필',
    subject: 'Science',
    type: 'Mathematical Modeling',
    grade: 'USA grade 3',
    unit: 'Time',
    detailed_section: 'Numbers from 0 to 120',
    difficulty: 2,
    title: 'USA grade 6th Variables and expressions',
    description: '- 8문제',
    price: '10.50',
    pages: 5,
    problems: 28,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: 'usa_science_11_problems.pdf',
    updated_date: '2024-08-06T01:53:32.058132-04:00',
    created_date: '2024-08-06T01:53:32.058156-04:00',
  },
  {
    id: 3,
    write_user_name: '김종필',
    subject: 'Math',
    type: 'Multiple Choice',
    grade: 'Geometry',
    unit: 'Performing transformations',
    detailed_section: 'Introduction to rigid transformations',
    difficulty: 'Medium',
    title: 'Q1 Geometry Performing transformations',
    description:
      'Real-world problem situations: Emily and Jacob are planning to buy gifts for their friends. Emily bought 3 notebooks and 2 pens for a total...',
    price: '1.00',
    pages: 5,
    problems: 25,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 4,
    write_user_name: '김종필',
    subject: 'Math',
    type: 'Math for Literacy',
    grade: 'Geometry',
    unit: 'Right triangles & trigonometry',
    detailed_section: 'Introduction to trigonometry',
    difficulty: 'Medium',
    title: 'Q2 Geometry Right triangles & trigonometry',
    description:
      'Given a right triangle where one of the angles is 30° and the opposite side to this angle is 5 units, find the length of the hypotenuse...',
    price: '1.00',
    pages: 5,
    problems: 25,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 5,
    write_user_name: '김종필',
    subject: 'Math',
    type: 'Short Answer',
    grade: 'Algebra',
    unit: 'Linear equations',
    detailed_section: 'Solving linear equations',
    difficulty: 'Medium',
    title: 'Q3 Algebra Linear equations',
    description:
      'Solve for x in the equation 2x + 3 = 7. Find the value of x that satisfies this equation...',
    price: '1.50',
    pages: 5,
    problems: 20,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 6,
    write_user_name: '김종필',
    subject: 'Math',
    type: 'Mathematical Modeling',
    grade: 'Calculus',
    unit: 'Derivatives',
    detailed_section: 'Differentiation',
    difficulty: 'Hard',
    title: 'Q4 Calculus Derivatives',
    description:
      'Differentiate the function f(x) = 3x^2 + 2x - 5. Find the derivative of the function and explain each step...',
    price: '2.00',
    pages: 5,
    problems: 15,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 7,
    write_user_name: '김종필',
    subject: 'Science',
    type: 'Short Answer',
    grade: 'Physics',
    unit: "Newton's laws",
    detailed_section: 'Classical mechanics',
    difficulty: 'Medium',
    title: "Q5 Physics Newton's laws",
    description:
      "Describe Newton's three laws of motion and provide examples for each. Explain how these laws apply to real-world scenarios...",
    price: '1.75',
    pages: 6,
    problems: 30,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 8,
    write_user_name: '김종필',
    subject: 'Science',
    type: 'Multiple Choice',
    grade: 'Chemistry',
    unit: 'Periodic table',
    detailed_section: 'Element properties',
    difficulty: 'Easy',
    title: 'Q6 Chemistry Periodic table',
    description:
      'Explain the organization of the periodic table and describe the properties of different groups and periods. Discuss the trends in element properties...',
    price: '1.25',
    pages: 4,
    problems: 25,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 9,
    write_user_name: '김종필',
    subject: 'Science',
    type: 'Math for Literacy',
    grade: 'Biology',
    unit: 'Cell structure',
    detailed_section: 'Cell biology',
    difficulty: 'Medium',
    title: 'Q7 Biology Cell structure',
    description:
      'Describe the structure of a typical eukaryotic cell. Identify the functions of major organelles and explain how they contribute to cell function...',
    price: '1.50',
    pages: 5,
    problems: 20,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 10,
    write_user_name: '김종필',
    subject: 'Liberal Arts',
    type: 'Essay',
    grade: 'History',
    unit: 'World War II',
    detailed_section: 'Modern history',
    difficulty: 'Hard',
    title: 'Q8 History World War II',
    description:
      'Provide an overview of the major events of World War II. Discuss the causes, significant battles, and the consequences of the war...',
    price: '2.50',
    pages: 6,
    problems: 10,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 11,
    write_user_name: '김종필',
    subject: 'Liberal Arts',
    type: 'Essay',
    grade: 'Literature',
    unit: "Shakespeare's plays",
    detailed_section: 'English literature',
    difficulty: 'Hard',
    title: "Q9 Literature Shakespeare's plays",
    description:
      "Analyze the themes and characters of one of Shakespeare's plays. Discuss the historical context and its impact on modern literature...",
    price: '3.00',
    pages: 5,
    problems: 5,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
  {
    id: 12,
    write_user_name: '김종필',
    subject: 'Science',
    type: 'Essay',
    grade: 'Geography',
    unit: 'Climate change',
    detailed_section: 'Environmental science',
    difficulty: 'Medium',
    title: 'Q10 Geography Climate change',
    description:
      'Explain the causes and effects of climate change. Discuss the evidence supporting climate change and the potential solutions to mitigate its impact...',
    price: '1.75',
    pages: 5,
    problems: 15,
    preview_image:
      'https://studyola-main-dir.s3.us-east-2.amazonaws.com/pre_image/preview.jpeg',
    file_name: '2024.06.11_Payment_User_Flow.pdf',
    updated_date: '2024-08-06T01:51:33.351816-04:00',
    created_date: '2024-08-06T01:51:33.351846-04:00',
  },
];
